/** Core A1 French → English. Keys are written in normal French; the glossary normalises them. */
export const coreFrenchToEnglish: Record<string, string> = {
  je: 'I',
  tu: 'you',
  il: 'he / it',
  elle: 'she / it',
  on: 'we / one',
  nous: 'we',
  vous: 'you',
  ils: 'they',
  elles: 'they',
  me: 'me',
  te: 'you',
  se: 'himself / herself',
  moi: 'me',
  toi: 'you',
  lui: 'him',
  eux: 'them',
  le: 'the / him / it',
  la: 'the / her / it',
  l: 'the',
  les: 'the / them',
  un: 'a / one',
  une: 'a / one',
  des: 'some / of the',
  du: 'some / of the',
  de: 'of / from',
  d: 'of / from',
  à: 'to / at',
  au: 'to the / at the',
  aux: 'to the / at the',
  en: 'in / to',
  y: 'there',
  et: 'and',
  ou: 'or',
  mais: 'but',
  donc: 'so',
  car: 'because',
  ni: 'nor',
  si: 'if / yes',
  ne: 'not',
  pas: 'not',
  plus: 'more / no more',
  jamais: 'never',
  rien: 'nothing',
  personne: 'nobody / person',
  que: 'that / what',
  qui: 'who',
  quoi: 'what',
  dont: 'whose / of which',
  où: 'where',
  quand: 'when',
  comment: 'how',
  pourquoi: 'why',
  parce: 'because',
  'parce que': 'because',
  oui: 'yes',
  non: 'no',
  merci: 'thank you',
  "s'il te plaît": 'please',
  "s'il vous plaît": 'please',
  sil: 'please',
  bonjour: 'hello',
  bonsoir: 'good evening',
  salut: 'hi',
  'au revoir': 'goodbye',
  'à bientôt': 'see you soon',
  'à tout à l’heure': 'see you in a bit',
  bienvenue: 'welcome',
  allô: 'hello (phone)',
  excusez: 'excuse me',
  'excusez-moi': 'excuse me',
  pardon: 'sorry / pardon',
  être: 'to be',
  avoir: 'to have',
  faire: 'to do / to make',
  aller: 'to go',
  venir: 'to come',
  voir: 'to see',
  savoir: 'to know',
  pouvoir: 'can / to be able to',
  vouloir: 'to want',
  devoir: 'must / to have to',
  dire: 'to say',
  parler: 'to speak',
  écouter: 'to listen',
  regarder: 'to look / to watch',
  aimer: 'to like / to love',
  habiter: 'to live',
  manger: 'to eat',
  boire: 'to drink',
  prendre: 'to take',
  donner: 'to give',
  arriver: 'to arrive',
  partir: 'to leave',
  rester: 'to stay',
  travailler: 'to work',
  étudier: 'to study',
  apprendre: 'to learn',
  comprendre: 'to understand',
  demander: 'to ask',
  répondre: 'to answer',
  appeler: 'to call',
  sappeler: 'to be called',
  "s'appeler": 'to be called',
  suis: 'am',
  es: 'are',
  est: 'is',
  sommes: 'are',
  êtes: 'are',
  sont: 'are',
  ai: 'have',
  as: 'have',
  a: 'has / to / at',
  avons: 'have',
  avez: 'have',
  ont: 'have',
  vais: 'go / am going',
  vas: 'go / are going',
  va: 'goes / is going',
  allons: 'go / let’s go',
  allez: 'go',
  vont: 'go',
  fais: 'do / make',
  fait: 'does / made',
  faisons: 'do / make',
  faites: 'do / make',
  font: 'do / make',
  peux: 'can',
  peut: 'can',
  pouvons: 'can',
  pouvez: 'can',
  peuvent: 'can',
  veux: 'want',
  veut: 'wants',
  voulons: 'want',
  voulez: 'want',
  veulent: 'want',
  dois: 'must',
  doit: 'must',
  devons: 'must',
  devez: 'must',
  doivent: 'must',
  ce: 'this / that',
  cet: 'this / that',
  cette: 'this / that',
  ces: 'these / those',
  ça: 'that / it',
  cela: 'that',
  c: 'it / that',
  "c'est": 'it is',
  cest: "it's",
  'il y a': 'there is / there are',
  'il faut': 'one must / you need to',
  mon: 'my',
  ma: 'my',
  mes: 'my',
  ton: 'your',
  ta: 'your',
  tes: 'your',
  son: 'his / her / its',
  sa: 'his / her / its',
  ses: 'his / her / its',
  notre: 'our',
  nos: 'our',
  votre: 'your',
  vos: 'your',
  leur: 'their',
  leurs: 'their',
  avec: 'with',
  sans: 'without',
  pour: 'for',
  par: 'by / through',
  dans: 'in',
  sur: 'on',
  sous: 'under',
  chez: 'at the home of',
  entre: 'between',
  vers: 'towards',
  après: 'after',
  avant: 'before',
  pendant: 'during',
  depuis: 'since / for',
  trop: 'too / too much',
  très: 'very',
  bien: 'well / good',
  mal: 'badly / bad',
  peu: 'little / few',
  beaucoup: 'a lot',
  assez: 'enough',
  moins: 'less',
  aussi: 'also / too',
  encore: 'again / still',
  déjà: 'already',
  maintenant: 'now',
  aujourd: 'today',
  "aujourd'hui": 'today',
  demain: 'tomorrow',
  hier: 'yesterday',
  matin: 'morning',
  midi: 'noon',
  soir: 'evening',
  nuit: 'night',
  jour: 'day',
  semaine: 'week',
  mois: 'month',
  an: 'year',
  année: 'year',
  heure: 'hour / time',
  minute: 'minute',
  lundi: 'Monday',
  mardi: 'Tuesday',
  mercredi: 'Wednesday',
  jeudi: 'Thursday',
  vendredi: 'Friday',
  samedi: 'Saturday',
  dimanche: 'Sunday',
  homme: 'man',
  femme: 'woman',
  enfant: 'child',
  ami: 'friend',
  amie: 'friend',
  famille: 'family',
  père: 'father',
  mère: 'mother',
  frère: 'brother',
  sœur: 'sister',
  fils: 'son',
  fille: 'daughter / girl',
  nom: 'name / last name',
  prénom: 'first name',
  âge: 'age',
  ans: 'years old',
  pays: 'country',
  ville: 'city',
  quartier: 'neighbourhood',
  rue: 'street',
  maison: 'house',
  appartement: 'flat / apartment',
  école: 'school',
  université: 'university',
  travail: 'work',
  métier: 'job',
  bureau: 'office / desk',
  magasin: 'shop',
  marché: 'market',
  restaurant: 'restaurant',
  café: 'coffee / café',
  thé: 'tea',
  eau: 'water',
  pain: 'bread',
  fromage: 'cheese',
  viande: 'meat',
  poisson: 'fish',
  fruit: 'fruit',
  légume: 'vegetable',
  table: 'table',
  chaise: 'chair',
  lit: 'bed',
  chambre: 'bedroom / room',
  cuisine: 'kitchen / cooking',
  voiture: 'car',
  train: 'train',
  bus: 'bus',
  métro: 'metro',
  avion: 'plane',
  billet: 'ticket',
  hôtel: 'hotel',
  valise: 'suitcase',
  téléphone: 'phone',
  ordinateur: 'computer',
  livre: 'book',
  cahier: 'notebook',
  stylo: 'pen',
  chien: 'dog',
  chat: 'cat',
  temps: 'time / weather',
  soleil: 'sun',
  pluie: 'rain',
  neige: 'snow',
  chaud: 'hot',
  froid: 'cold',
  petit: 'small',
  petite: 'small',
  grand: 'big / tall',
  grande: 'big / tall',
  bon: 'good',
  bonne: 'good',
  mauvais: 'bad',
  belle: 'beautiful',
  beau: 'beautiful',
  nouveau: 'new',
  nouvelle: 'new',
  vieux: 'old',
  vieille: 'old',
  jeune: 'young',
  facile: 'easy',
  difficile: 'difficult',
  cher: 'expensive / dear',
  chère: 'expensive / dear',
  ouvert: 'open',
  fermé: 'closed',
  ici: 'here',
  là: 'there',
  loin: 'far',
  près: 'near',
  gauche: 'left',
  droite: 'right',
  haut: 'high / top',
  bas: 'low / bottom',
  combien: 'how much / how many',
  quel: 'which / what',
  quelle: 'which / what',
  quels: 'which / what',
  quelles: 'which / what',
  tout: 'all / everything',
  toute: 'all',
  tous: 'all',
  toutes: 'all',
  autre: 'other',
  même: 'same / even',
  chaque: 'each',
  deux: 'two',
  trois: 'three',
  quatre: 'four',
  cinq: 'five',
  six: 'six',
  sept: 'seven',
  huit: 'eight',
  neuf: 'nine',
  dix: 'ten',
  euro: 'euro',
  euros: 'euros',
  s: 'if / his',
  n: 'not',
  m: 'me / my',
  t: 'you',
  j: 'I',
  qu: 'that / what',
}
