/** Extra A1 / course words so hover tooltips cover study instructions and unit vocabulary. */
export const extraFrenchToEnglish: Record<string, string> = {
  clavier: 'keyboard',
  entendre: 'to hear',
  "l'entendre": 'hear it',
  entends: 'hear',
  entend: 'hears',
  entendons: 'hear',
  entendez: 'hear',
  entendent: 'hear',
  entraîner: 'to train / to practise',
  entraîne: 'trains / practise',
  entraînes: 'train / practise',
  entraînons: 'train / practise',
  entraînez: 'train / practise',
  entraînent: 'train / practise',
  "t'entraînes": 'you practise',
  "s'entraîne": 'practises',
  "s'entraîner": 'to practise',
  épeler: 'to spell',
  épelle: 'spell',
  épelles: 'spell',
  épelons: 'spell',
  épelez: 'spell',
  épelent: 'spell',
  espace: 'space',
  espaces: 'spaces',
  accent: 'accent',
  accents: 'accents',
  compter: 'to count',
  compte: 'counts / account',
  comptent: 'count',
  lettre: 'letter',
  lettres: 'letters',
  base: 'base / basic',
  mot: 'word',
  mots: 'words',
  phrase: 'sentence',
  phrases: 'sentences',
  texte: 'text',
  textes: 'texts',
  exercice: 'exercise',
  exercices: 'exercises',
  activité: 'activity',
  activités: 'activities',
  leçon: 'lesson',
  leçons: 'lessons',
  unité: 'unit',
  unités: 'units',
  carte: 'map / card',
  cartes: 'maps / cards',
  modèle: 'model',
  scène: 'scene',
  oral: 'spoken / oral',
  écrit: 'written / wrote',
  écrite: 'written',
  politesse: 'politeness',
  librairie: 'bookshop',
  libraire: 'bookseller',
  seulement: 'only',
  puis: 'then',
  souvent: 'often',
  surtout: 'especially',
  comme: 'like / as',
  français: 'French',
  française: 'French',
  francophone: 'French-speaking',
  francophones: 'French-speaking people',
  féminin: 'feminine',
  masculin: 'masculine',
  pluriel: 'plural',
  singulier: 'singular',
  verbe: 'verb',
  verbes: 'verbs',
  infinitif: 'infinitive',
  article: 'article',
  articles: 'articles',
  adjectif: 'adjective',
  nom: 'name / noun',
  noms: 'names / nouns',
  voyelle: 'vowel',
  voyelles: 'vowels',
  consonne: 'consonant',
  négation: 'negation',
  question: 'question',
  questions: 'questions',
  réponse: 'answer',
  ordre: 'order',
  remettre: 'to put back',
  remets: 'put back',
  remettez: 'put back',
  écouter: 'to listen',
  écoute: 'listen',
  écoutes: 'listen',
  écoutons: 'listen',
  écoutez: 'listen',
  écoutent: 'listen',
  répéter: 'to repeat',
  répète: 'repeat',
  répétez: 'repeat',
  choisir: 'to choose',
  choisis: 'choose',
  choisit: 'chooses',
  toucher: 'to touch / to tap',
  touche: 'tap / key',
  cliquer: 'to click',
  lire: 'to read',
  lis: 'read',
  lit: 'reads / bed',
  lisons: 'read',
  lisez: 'read',
  disent: 'say',
  dit: 'says / said',
  dire: 'to say',
  présenter: 'to introduce / to present',
  présente: 'introduce / present',
  présentes: 'introduce',
  habiter: 'to live',
  habite: 'live',
  habites: 'live',
  habitons: 'live',
  habitez: 'live',
  habitent: 'live',
  aimer: 'to like',
  aime: 'like',
  aimes: 'like',
  aimons: 'like',
  aimez: 'like',
  aiment: 'like',
  adore: 'love',
  adores: 'love',
  "j'adore": 'I love',
  préfère: 'prefer',
  préfères: 'prefer',
  préférer: 'to prefer',
  chercher: 'to look for',
  cherche: 'look for',
  cherches: 'look for',
  demander: 'to ask',
  demande: 'ask / request',
  payer: 'to pay',
  paie: 'pay',
  payez: 'pay',
  prendre: 'to take',
  prends: 'take',
  prend: 'takes',
  prenons: 'take',
  prenez: 'take',
  prennent: 'take',
  venir: 'to come',
  viens: 'come',
  vient: 'comes',
  venons: 'come',
  venez: 'come',
  viennent: 'come',
  voyage: 'trip / travel',
  voyager: 'to travel',
  voyages: 'trips',
  prix: 'price',
  plat: 'dish',
  plats: 'dishes',
  menu: 'menu',
  goût: 'taste',
  goûts: 'tastes',
  sport: 'sport',
  cinéma: 'cinema',
  musée: 'museum',
  parc: 'park',
  bus: 'bus',
  transports: 'transport',
  quotidien: 'everyday',
  quotidienne: 'everyday',
  métier: 'job',
  métiers: 'jobs',
  ami: 'friend',
  amis: 'friends',
  amie: 'friend',
  amies: 'friends',
  parents: 'parents',
  personne: 'person / nobody',
  personnes: 'people',
  message: 'message',
  courriel: 'email',
  téléphone: 'phone',
  nationalité: 'nationality',
  nationalités: 'nationalities',
  capitale: 'capital',
  pays: 'country',
  classe: 'class',
  journée: 'day',
  jours: 'days',
  heures: 'hours',
  fois: 'time(s)',
  sac: 'bag',
  pull: 'jumper / sweater',
  vêtement: 'item of clothing',
  vêtements: 'clothes',
  robe: 'dress',
  chemise: 'shirt',
  pantalon: 'trousers',
  chaussures: 'shoes',
  passé: 'past',
  futur: 'future',
  composé: 'compound / composed',
  "d'accord": 'OK / agreed',
  accord: 'agreement',
  "s'il": 'if he / please',
  plaît: 'please / pleases',
  revoir: 'goodbye / see again',
  allô: 'hello (phone)',
  canada: 'Canada',
  canadien: 'Canadian',
  canadienne: 'Canadian',
  suisse: 'Swiss / Switzerland',
  québec: 'Quebec',
  paris: 'Paris',
  lyon: 'Lyon',
  devant: 'in front of',
  "week-end": 'weekend',
  week: 'week',
  end: 'end',
  rendez: 'go (rendez-vous)',
  'rendez-vous': 'appointment / date',
  réveille: 'wake up',
  réveiller: 'to wake',
  "je m'appelle": 'my name is',
  "m'appelle": 'my name is',
  appelle: 'call / is called',
  appeler: 'to call',
  "n'est": 'is not',
  "n'aime": 'do not like',
  "n'y": 'not there',
  "j'ai": 'I have',
  "c'était": 'it was',
  "qu'est": 'what is',
  "d'un": 'of a',
  lieu: 'place',
  lieux: 'places',
  faut: 'must / need to',
  vingt: 'twenty',
  code: 'code',
  alors: 'so / then',
  donc: 'so',
  ensuite: 'then / next',
  dabord: 'first',
  "d'abord": 'first',
  enfin: 'finally',
  toujours: 'always',
  parfois: 'sometimes',
  encore: 'again / still',
  déjà: 'already',
  maintenant: 'now',
  aujourd: 'today',
  "aujourd'hui": 'today',
  bientôt: 'soon',
  tard: 'late',
  tôt: 'early',
  facile: 'easy',
  difficile: 'difficult',
  possible: 'possible',
  important: 'important',
  pratique: 'practical / practise',
  consigne: 'instruction',
  consignes: 'instructions',
  alphabet: 'alphabet',
  prénom: 'first name',
  identité: 'identity',
  document: 'document',
  passeport: 'passport',
  billet: 'ticket',
  reservation: 'booking',
  réservation: 'booking',
  chambre: 'room',
  hôtel: 'hotel',
  gare: 'station',
  aéroport: 'airport',
  vol: 'flight',
  valise: 'suitcase',
  bagage: 'luggage',
  restaurant: 'restaurant',
  café: 'coffee / café',
  thé: 'tea',
  eau: 'water',
  pain: 'bread',
  beurre: 'butter',
  fromage: 'cheese',
  salade: 'salad',
  viande: 'meat',
  poisson: 'fish',
  dessert: 'dessert',
  entrée: 'starter',
  addition: 'bill',
  euro: 'euro',
  euros: 'euros',
  cher: 'expensive',
  bon: 'good',
  bonne: 'good',
  mauvais: 'bad',
  petit: 'small',
  grande: 'big',
  grand: 'big / tall',
  beau: 'beautiful',
  belle: 'beautiful',
  nouveau: 'new',
  nouvelle: 'new',
  vieux: 'old',
  jeune: 'young',
  chaud: 'hot',
  froid: 'cold',
  ouvert: 'open',
  fermé: 'closed',
  libre: 'free',
  occupé: 'busy',
  content: 'happy',
  fatigué: 'tired',
  malade: 'ill',
  désolé: 'sorry',
  excusez: 'excuse me',
  pardon: 'sorry',
}
